# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.cache/wt [current_project]
set_property parent.project_path D:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  d:/Git/cuhk-ceng3430/Project/ip_repo/cube_renderer_3d_2.1
  d:/Git/cuhk-ceng3430/Project/ip_repo/cube_renderer_controller_2.0
  d:/Git/cuhk-ceng3430/Project/ip_repo/cube_renderer_controller_2.0
  d:/Git/cuhk-ceng3430/Project/ip_repo/object_renderer_controller_1.0
} [current_project]
set_property ip_output_repo d:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/hdl/cube_renderering_system_wrapper.vhd
add_files D:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/cube_renderering_system.bd
set_property used_in_implementation false [get_files -all d:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/ip/cube_renderering_system_processing_system7_0_0/cube_renderering_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/ip/cube_renderering_system_rst_ps7_0_50M_0/cube_renderering_system_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/ip/cube_renderering_system_rst_ps7_0_50M_0/cube_renderering_system_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/ip/cube_renderering_system_rst_ps7_0_50M_0/cube_renderering_system_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/ip/cube_renderering_system_auto_pc_0/cube_renderering_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/cube_renderering_system_ooc.xdc]
set_property is_locked true [get_files D:/Git/cuhk-ceng3430/Project/ceng3430_proj_renderer3d/ceng3430_proj_renderer3d.srcs/sources_1/bd/cube_renderering_system/cube_renderering_system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Git/cuhk-ceng3430/Project/constrs/board.xdc
set_property used_in_implementation false [get_files D:/Git/cuhk-ceng3430/Project/constrs/board.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top cube_renderering_system_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef cube_renderering_system_wrapper.dcp

catch { report_utilization -file cube_renderering_system_wrapper_utilization_synth.rpt -pb cube_renderering_system_wrapper_utilization_synth.pb }
