#include "cube_renderer_controller_interface.h"

u32 get_btn(int BTN)
{
    return CUBE_RENDERER_CONTROLLER_mReadReg(BASEADDR, INPUT_ADDR) & BTN;
}

u32 get_sw()
{
    return (CUBE_RENDERER_CONTROLLER_mReadReg(BASEADDR, INPUT_ADDR));
}

u32 get_sw_n(int n)
{
    return (CUBE_RENDERER_CONTROLLER_mReadReg(BASEADDR, INPUT_ADDR) & n);
}

void write_vertices(float v[8][2])
{
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG0_OFFSET, (u32)round(v[0][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG1_OFFSET, (u32)round(v[0][1]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG2_OFFSET, (u32)round(v[1][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG3_OFFSET, (u32)round(v[1][1]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG4_OFFSET, (u32)round(v[2][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG5_OFFSET, (u32)round(v[2][1]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG6_OFFSET, (u32)round(v[3][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG7_OFFSET, (u32)round(v[3][1]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG8_OFFSET, (u32)round(v[4][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG9_OFFSET, (u32)round(v[4][1]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG10_OFFSET,
                                       (u32)round(v[5][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG11_OFFSET,
                                       (u32)round(v[5][1]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG12_OFFSET,
                                       (u32)round(v[6][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG13_OFFSET,
                                       (u32)round(v[6][1]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG14_OFFSET,
                                       (u32)round(v[7][0]));
    CUBE_RENDERER_CONTROLLER_mWriteReg(BASEADDR, CUBE_RENDERER_CONTROLLER_S00_AXI_SLV_REG15_OFFSET,
                                       (u32)round(v[7][1]));
}